DECLARE
V_NAME EMPLOYEE2.FNAME%TYPE;
V_JOB EMPLOYEE2.JOB%TYPE;
V_SAL EMPLOYEE2.SALARY%TYPE;
BEGIN
SELECT FNAME,JOB,SALARY INTO V_NAME,V_JOB,V_SAL FROM EMPLOYEE2 WHERE SSN=12;
DBMS_OUTPUT.PUT_LINE(V_NAME||''||V_JOB||''||V_SAL);
END;
/