DECLARE
A NUMBER(2):=&VALUE_OF_A;
B NUMBER(2):=&VALUE_OF_B;
BEGIN
IF A<B THEN
DBMS_OUTPUT.PUT_LINE('SMALLER VALUE IS '||A);
ELSIF A>B THEN
DBMS_OUTPUT.PUT_LINE('SMALLER VALUE IS '||B);
ELSE
DBMS_OUTPUT.PUT_LINE('BOTH NO. ARE EQUAL');
END IF;
END;
/
